import NavBar from "@/components/navBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" selection:bg-black selection:text-white ">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
